[package]
name = "rs_loglib"
version = "0.1.0"
edition = "2021"

[dependencies]
parking_lot = "0.12"
tracing = "0.1"
tracing-appender = "0.2"
time = { version = "0.3", features = ["formatting", "local-offset", "macros"] }
lazy_static = "1.4.0"
